server:
  servlet:
    context-path: /lmproject4/

spring:
  application.name: LMProject
  # jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServerDialect
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Project4
    username: sa
    password: 123